name: Node.js Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
       - uses: actions/checkout@v4
       - name: Setup dotnet 6.x
         uses: actions/setup-dotnet@v3
         with:
           dotnet-version: '6.x'
       - name: Build
         run: dotnet build
  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/poohinq
      - run: npm i
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
